<?php
//
// File generated by ... on the 2022-12-15T01:24:47+0100
// Please do not edit manually
//

/**
 * Classes and menus for combodo-webhook-integration (version 1.1.1)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class EventWebhook extends EventNotification
{
	public static function Init()
	{
		$aParams = array(			'category' => 'core/cmdb,view_in_gui',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => 'priv_event_webhook',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),
			'order_by_default' => array('date' => false),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("action_finalclass", array("allowed_values"=>null, "sql"=>'action_finalclass', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("webhook_url", array("allowed_values"=>null, "sql"=>'webhook_url', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("headers", array("allowed_values"=>null, "sql"=>'headers', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("payload", array("allowed_values"=>null, "sql"=>'payload', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeLongText("response", array("allowed_values"=>null, "sql"=>'response', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'date',
  1 => 'message',
  2 => 'action_finalclass',
  3 => 'webhook_url',
  4 => 'headers',
  5 => 'payload',
  6 => 'response',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'date',
  1 => 'message',
  2 => 'webhook_url',
));
;
	}


}


class RemoteApplicationType extends Typology
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'remoteapplicationtype',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-remote-application-type-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeLinkedSet("remoteapplicationconnections_list", array("linked_class"=>'RemoteApplicationConnection', "ext_key_to_me"=>'remoteapplicationtype_id', "count_min"=>0, "count_max"=>0, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'name',
  1 => 'remoteapplicationconnections_list',
));
;
	}


}


class RemoteApplicationConnection extends Typology
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'application', 'environment'),
			'db_table' => 'remoteapplicationconnection',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-remote-application-connection-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("remoteapplicationtype_id", array("targetclass"=>'RemoteApplicationType', "allowed_values"=>null, "sql"=>'remoteapplicationtype_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("environment", array("allowed_values"=>new ValueSetEnum("1-development,2-test,3-production"), "display_style"=>'list', "sql"=>'environment', "default_value"=>'2-test', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("url", array("allowed_values"=>null, "sql"=>'url', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeLinkedSet("actions_list", array("linked_class"=>'ActionWebhook', "ext_key_to_me"=>'remoteapplicationconnection_id', "count_min"=>0, "count_max"=>0, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:RemoteApplicationConnection:baseinfo' => 
    array (
      0 => 'name',
      1 => 'remoteapplicationtype_id',
      2 => 'environment',
      3 => 'url',
    ),
  ),
  0 => 'actions_list',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'remoteapplicationtype_id',
  2 => 'environment',
  3 => 'url',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'remoteapplicationtype_id',
  1 => 'environment',
  2 => 'url',
));
;
	}


}


class RemoteiTopConnection extends RemoteApplicationConnection
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'application', 'environment'),
			'db_table' => 'remoteitopconnection',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("auth_user", array("allowed_values"=>null, "sql"=>'auth_user', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributePassword("auth_pwd", array("allowed_values"=>null, "sql"=>'auth_pwd', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("version", array("allowed_values"=>null, "sql"=>'version', "default_value"=>'1.3', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:RemoteApplicationConnection:baseinfo' => 
    array (
      0 => 'name',
      1 => 'remoteapplicationtype_id',
      2 => 'environment',
      3 => 'url',
      4 => 'version',
    ),
    'fieldset:RemoteApplicationConnection:authinfo' => 
    array (
      0 => 'auth_user',
      1 => 'auth_pwd',
    ),
  ),
  0 => 'actions_list',
));
;
	}


}


class ActionWebhook extends Combodo\iTop\Core\Notification\Action\_ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_webhook',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeApplicationLanguage("language", array("allowed_values"=>null, "sql"=>'language', "default_value"=>'EN US', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("remoteapplicationconnection_id", array("targetclass"=>'RemoteApplicationConnection', "allowed_values"=>null, "sql"=>'remoteapplicationconnection_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("test_remoteapplicationconnection_id", array("targetclass"=>'RemoteApplicationConnection', "allowed_values"=>null, "sql"=>'test_remoteapplicationconnection_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("method", array("allowed_values"=>new ValueSetEnum("get,post,put,patch,delete"), "display_style"=>'list', "sql"=>'method', "default_value"=>'post', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("headers", array("allowed_values"=>null, "sql"=>'headers', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("payload", array("allowed_values"=>null, "sql"=>'payload', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("prepare_payload_callback", array("allowed_values"=>null, "sql"=>'prepare_payload_callback', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("process_response_callback", array("allowed_values"=>null, "sql"=>'process_response_callback', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
      2 => 'method',
      3 => 'headers',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionWebhook:requestparameters' => 
    array (
      0 => 'payload',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'status',
  1 => 'language',
  2 => 'remoteapplicationconnection_id',
));
;
	}


	/**
	 * Helper to retrieve the \RemoteApplicationConnection used by $oAction.
	 * Can be used in response processing methods to know where the response comes from.
	 *
	 * @param \ActionWebhook $oAction
	 *
	 * @return \RemoteApplicationConnection {@see static::GetRemoteApplicationConnection}
	 */
	static public function GetRemoteApplicationConnectionFromActionWebhok($oAction)
	{
		return $oAction->GetRemoteApplicationConnection();
	}



	public function PrefillCreationForm(&$aContextParam)
	{
		// Set default content-type
		$this->Set('headers', 'Content-type: application/json');
	}


	/**
	 * @inheritDoc
	 */
	protected function PrepareWebRequest(array $aContextArgs, \EventNotification &$oLog)
	{
		// Switch to action language in order to have dictionary entries in the right language
		// Note: We save current user language so we can switch back to it afterwards
		$sUserLang = Dict::GetUserLanguage();
		Dict::SetUserLanguage($this->Get('language'));

		// Surround with try/catch to make sure to restore user language in case of crash and don't contaminate the rest of the app.
		try {
			// Get web request parameters
			// - URL
			$sURL = $this->PrepareURL($aContextArgs, $oLog);
			if (!is_null($oLog))
			{
				$oLog->Set('webhook_url', ($sURL !== null) ? $sURL : 'No test URL provided');
			}
			// - Method
			$sMethod = $this->PrepareMethod($aContextArgs, $oLog);
			// - Headers
			$aHeaders = $this->PrepareHeaders($aContextArgs, $oLog);
			if (!is_null($oLog))
			{
				$this->LogHeaders($this->Get('headers'), $aHeaders, $oLog);
				$this->TruncateLogAttributeForDB($oLog, 'headers');
			}
			// - Payload
			// ... Force payload to be prepared from callback in the method of this class (avoid polymorphic inheritance)
			if ($this->HasPreparePayloadCallback()) {
				$payload = self::PreparePayload($aContextArgs, $oLog);
			}
			// ... Payload can be prepared using the polymorphic inheritance
			else {
				$payload = $this->PreparePayload($aContextArgs, $oLog);
			}
			if (!is_null($oLog))
			{
				$this->LogPayload($this->Get('payload'), $payload, $oLog);
				$this->TruncateLogAttributeForDB($oLog, 'payload');
			}
		} catch (Exception $oException) {
			throw $oException;
		} finally {
			// Switch back to current user language
			Dict::SetUserLanguage($sUserLang);
		}

		// Get module parameters
		$sConnectionTimeoutInSeconds = MetaModel::GetModuleSetting('combodo-webhook-integration', 'timeout', \Combodo\iTop\Service\WebRequestSender::DEFAULT_CONNECTION_TIMEOUT_IN_SECONDS);

		// Prepare cURL options
		$aCURLOptions = array(
			CURLOPT_RETURNTRANSFER => true,
			// Note: Even though we might have something else than "get" and "post" in the $sMethod, for now we only set it to these 2 values in the cURL options. It should be reworked / fixed.
			CURLOPT_POST => ($sMethod === 'post'),
			// Note: We pass headers as a cURL option to avoid  bug N°3267 in \utils::DoPostRequest()
			CURLOPT_HTTPHEADER => $aHeaders,
			CURLOPT_CONNECTTIMEOUT => $sConnectionTimeoutInSeconds,
			CURLOPT_POSTFIELDS => $payload,
		);

		// Certificate options
		// - Should we check its validity?
		if (MetaModel::GetModuleSetting('combodo-webhook-integration', 'certificate_check', true))
		{
			$aCURLOptions[CURLOPT_SSL_VERIFYPEER] = true;
			$aCURLOptions[CURLOPT_SSL_VERIFYHOST] = 2;
		}
		else
		{
			$aCURLOptions[CURLOPT_SSL_VERIFYPEER] = false;
			$aCURLOptions[CURLOPT_SSL_VERIFYHOST] = 0;
		}
		// - Location of CA certificate file
		$sCACertFile = MetaModel::GetModuleSetting('combodo-webhook-integration', 'ca_certificate_file', '');
		if (!empty($sCACertFile))
		{
			// The name of a file containing a PEM formatted certificate.
			$aCurlOptions[CURLOPT_SSLCERT] = $sCACertFile;
		}

		$oWebRequest = new \Combodo\iTop\Core\WebRequest($sURL);
		$oWebRequest->SetOptions($aCURLOptions);

		return $oWebRequest;
	}


	/**
	 * Return the URL for the web request
	 *
	 * @param array              $aContextArgs
	 * @param \EventNotification $oLog
	 *
	 * @return string
	 * @throws \ArchivedObjectException
	 * @throws \CoreException
	 * @throws \Exception
	 */
	protected function PrepareURL(array $aContextArgs, \EventNotification &$oLog)
	{
		$oRemoteApplicationConnection = $this->GetRemoteApplicationConnection();

		// Get URL
		if($oRemoteApplicationConnection !== null)
		{
			$sURL = MetaModel::ApplyParams($oRemoteApplicationConnection->Get('url'), $aContextArgs);
		}
		elseif($this->IsBeingTested())
		{
			$sURL = null;
		}
		else
		{

			throw new Exception('Action should have at least one webhook URL set!');
		}

		return $sURL;
	}


	/**
	 * Return the web request method (get or post)
	 *
	 * @param array              $aContextArgs
	 * @param \EventNotification $oLog
	 *
	 * @return string
	 * @throws \ArchivedObjectException
	 * @throws \CoreException
	 */
	protected function PrepareMethod(array $aContextArgs, \EventNotification &$oLog)
	{
		return $this->Get('method');
	}


	/**
	 * Return HTTP headers of the action as an array (eg. ['Key 1: Value 1', 'Key 2: Value 2']).
	 * If no headers specified, 'Content-type: application/json' will be returned as it is the standard for most webhook apps.
	 *
	 * IMPORTANT: The array must be NON associative, otherwise the cURL lib. won't use it.
	 *
	 * @param array              $aContextArgs
	 * @param \EventNotification $oLog
	 *
	 * @return array
	 * @throws \ArchivedObjectException
	 * @throws \CoreException
	 */
	protected function PrepareHeaders(array $aContextArgs, \EventNotification &$oLog)
	{
		$aHeaders = [];

		$sHeadersAsText = MetaModel::ApplyParams($this->Get('headers'), $aContextArgs);
		$aLines = preg_split('/\r\n|\r|\n/', $sHeadersAsText);
		foreach ($aLines as $sLine) {
			$sLine = trim($sLine);
			if (empty($sLine)) {
				continue;
			}

			$aHeaders[] = $sLine;
		}

		if (count($aHeaders) === 0) {
			$aHeaders[] = 'Content-type: application/json';
		}

		return $aHeaders;
	}


	/**
	 * Prepare the payload by formatting it, applying parameters and return it either as:
	 * - a string (eg. JSON encoded)
	 * - an array of parameters
	 *
	 * @param array              $aContextArgs
	 * @param \EventNotification $oLog
	 *
	 * @return string|array
	 * @throws \ArchivedObjectException
	 * @throws \CoreException
	 * @throws \Exception
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		$sCallbackFQCN = $this->Get('prepare_payload_callback');
		if (empty($sCallbackFQCN))
		{
			// Convert / encode payload depending on the content-type header
			$sContentType = null;
			$aHeaders = $this->PrepareHeaders($aContextArgs, $oLog);
			foreach ($aHeaders as $sHeader) {
				preg_match('/(Content-type)[\s]*:[\s]*(.*)/', $sHeader, $aMatches);
			    if (strlen($aMatches[2]) > 0){
					$sContentType = $aMatches[2];
					break;
				}
			}

			switch ($sContentType) {
				case 'application/json':
					// Apply params to payload recursively, to send properly encoded JSON
					$payload = $this->ApplyParamsToJson($aContextArgs, $this->Get('payload'));
					break;

				default:
					$payload = MetaModel::ApplyParams($this->Get('payload'), $aContextArgs);
					break;
			}
		}
		else
		{
			/** @var \DBObject $oTriggeringObject */
			$oTriggeringObject = $aContextArgs['this->object()'];

			// Check if callback is on the object itself
			if(stripos($sCallbackFQCN, '$this->') !== false)
			{
				$sMethodName = str_ireplace('$this->', '', $sCallbackFQCN);
				$payload = $oTriggeringObject->$sMethodName($aContextArgs, $oLog, $this);
			}
			// Otherwise, check if callback is callable as a static method
			elseif(is_callable($sCallbackFQCN))
			{
				$payload = call_user_func($sCallbackFQCN, $oTriggeringObject, $aContextArgs, $oLog, $this);
			}
			// Otherwise, there is a problem
			else
			{
				throw new Exception('Prepare payload callback is not callable ('.$sCallbackFQCN.')');
			}
		}

		return $payload;
	}


	/**
	 * Log raw and prepared headers in the event notification.
	 *
	 * "Authorization" header will obfuscated automatically.
	 * This method can be overloaded if you want to obfuscate other parts of what is logged (eg. credentials).
	 *
	 * @param string                $sRawHeaders
	 * @param array                 $aPreparedHeaders
	 * @param \EventNotification    $oLog
	 *
	 * @return void
	 */
	protected function LogHeaders($sRawHeaders, array $aPreparedHeaders, \EventNotification &$oLog)
	{
		// Obfuscate authorization header
		$sRegExp = '/^Authorization:(.+)$/m';
		$sAuthHeaderObfuscated = 'Authorization: ******';
		$sObfuscatedRawHeaders = preg_replace($sRegExp, $sAuthHeaderObfuscated, $sRawHeaders);
		$sObfuscatedPreparedHeaders = preg_replace($sRegExp, $sAuthHeaderObfuscated, implode("\n", $aPreparedHeaders));

		$oLog->Set('headers', "Raw:\n".$sObfuscatedRawHeaders."\n\nAfter preparation:\n".$sObfuscatedPreparedHeaders);
	}


	/**
	 * Log raw and prepared payload in the event notification.
	 * This method can be overloaded if you want to obfuscate parts of what is logged (eg. credentials).
	 *
	 * @param string                $sRawPayload
	 * @param string                $sPreparedPayload
	 * @param \EventNotification    $oLog
	 *
	 * @return void
	 */
	protected function LogPayload($sRawPayload, $sPreparedPayload, \EventNotification &$oLog)
	{
		$oLog->Set('payload', "Raw:\n".$sRawPayload."\n\nAfter preparation:\n".$sPreparedPayload);
	}


	/**
	 * Apply $aContextParams recursively to $aInputData
	 * @param array $aContextArgs
	 * @param array $aInputData Data to apply params to
	 *
	 * @see \MetaModel::ApplyParams
	 * @return array Same structure as $aInputData but with applied params
	 */
	protected function ApplyParamsToArray(array $aContextArgs, array $aInputData)
	{
		$aPreparedData = [];
		foreach ($aInputData as $sKey => $value) {
			$sPreparedKey = MetaModel::ApplyParams($sKey, $aContextArgs);
			$preparedValue = is_array($value) ? $this->ApplyParamsToArray($aContextArgs, $value) : MetaModel::ApplyParams($value, $aContextArgs);

			$aPreparedData[$sPreparedKey] = $preparedValue;
		}

		return $aPreparedData;
	}


	/**
	 * Apply $aContextParams to $sInputAsJson
	 * @param array $aContextArgs
	 * @param array $sInputAsJson JSON string to apply params to
	 *
	 * @see \MetaModel::ApplyParams
	 * @return string Same string as $sInputAsJson but with applied params
	 */
	protected function ApplyParamsToJson(array $aContextArgs, string $sInputAsJson)
	{
		$aInputAsArray = json_decode($sInputAsJson, true);
		if (false === is_array($aInputAsArray)) {
			IssueLog::Error('Wrong JSON format for input', 'console', ['input' => $sInputAsJson]);
			throw new Exception('Wrong JSON format for input, see error log for more information.');
		}

		$aPreparedDataAsArray = $this->ApplyParamsToArray($aContextArgs, $aInputAsArray);
		$sPreparedDataAsJson = json_encode($aPreparedDataAsArray);

		return $sPreparedDataAsJson;
	}


	/**
	 * Return the RemoteApplicationConnection to use depending on the current object status
	 *
	 * @return \RemoteApplicationConnection
	 */
	public function GetRemoteApplicationConnection()
	{
		// Get RemoteApplicationConnection object
		$sAttCode = $this->IsBeingTested() ? 'test_remoteapplicationconnection_id' : 'remoteapplicationconnection_id';
		$sID = $this->Get($sAttCode);

		/** @var \AttributeExternalKey $oAttDef */
		$oAttDef = MetaModel::GetAttributeDef(get_class($this), $sAttCode);
		$sClass = $oAttDef->GetTargetClass();

		return MetaModel::GetObject($sClass, $sID, false, true);
	}


	/**
	 * @return bool True if a callback is defined for preparing the payload
	 */
	public function HasPreparePayloadCallback()
	{
		return strlen($this->Get('prepare_payload_callback')) > 0;
	}


	/**
	 * @return bool True if a callback is defined to process the response
	 */
	public function HasProcessResponseCallback()
	{
		return strlen($this->Get('process_response_callback')) > 0;
	}


	/**
	 * Truncate the $sAttCode (based on its att. def.) to ensure that it fits in the DB
	 *
	 * @param \EventWebhook $oLog
	 * @param string $sAttCode

	 * @return void
	 * @since 1.0.1
	 */
	public function TruncateLogAttributeForDB(\EventWebhook &$oLog, $sAttCode)
	{
		$oAttDef = MetaModel::GetAttributeDef(get_class($oLog), $sAttCode);
		$iMaxSize = $oAttDef->GetMaxSize();
		$sFitText = $oLog->Get($sAttCode);
		$sEndingText = '[TRUNCATED]';
		// Note: We don't use mb_* functions as we don't want to cut after a whole character but after a certain byte length
		if ($iMaxSize && (strlen($sFitText) > $iMaxSize))
		{
			$sFitText = substr($sFitText, 0, $iMaxSize - strlen($sEndingText)) . $sEndingText;
			$oLog->Set($sAttCode, $sFitText);
		}
	}


}


class ActioniTopWebhook extends ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_itop_webhook',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-itop-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
      2 => 'headers',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionWebhook:requestparameters' => 
    array (
      0 => 'payload',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
;
	}


	/**
	 * Change Content-Type header
	 *
	 * @inheritDoc
	 */
	public function PrefillCreationForm(&$aContextParam)
	{
		// Set default content-type
		$this->Set("headers", "Content-type: application/x-www-form-urlencoded");
	}


	/**
	 * Add Authorization Basic header
	 *
	 * @inheritDoc
	 */
	protected function PrepareHeaders(array $aContextArgs, \EventNotification &$oLog)
	{
		$aHeaders = parent::PrepareHeaders($aContextArgs, $oLog);

		// Retrieve connection
		$oRemoteApplicationconnection = $this->GetRemoteApplicationConnection();

		// Prepare Basic Auth header
		$sAuthUser = MetaModel::ApplyParams($oRemoteApplicationconnection->Get('auth_user'), $aContextArgs);
		$sAuthPwd = MetaModel::ApplyParams($oRemoteApplicationconnection->Get('auth_pwd'), $aContextArgs);
		$sEncryptedCredentials = base64_encode("{$sAuthUser}:{$sAuthPwd}");

		$aHeaders[] = "Authorization: Basic {$sEncryptedCredentials}";

		return $aHeaders;
	}


	/**
	 * @inheritDoc
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		// Retrieve connection
		$oRemoteApplicationConnection = $this->GetRemoteApplicationConnection();

		// Retrieve basis parameters
		$aParameters = array(
			'version' => MetaModel::ApplyParams($oRemoteApplicationConnection->Get('version'), $aContextArgs),
			'json_data' => $this->ApplyParamsToJson($aContextArgs, $this->Get('payload')),  // Apply params to payload recursively
		);

		foreach($aParameters as $sParamName => $sParamValue)
		{
			if(empty($sParamValue))
			{
				throw new Exception('Missing at least of the following mandatory parameters: '.implode(', ', array_keys($aParameters)));
			}
		}

		// Transform array to HTTP query parameters (eg. https://target-url?version=XXX&json_data=XXX)
		return http_build_query($aParameters);
	}


	/**
	 * @inheritDoc
	 */
	protected function LogPayload($sRawPayload, $sPreparedPayload, \EventNotification &$oLog)
	{
		// Note: Credentials are no longer passed in the URL but we keep this in case we ever
		$sPwdQueryParamObfuscated = 'auth_pwd=******';
		$sObfuscatedPayload = preg_replace('/(auth_pwd=[^&]*)/', $sPwdQueryParamObfuscated, $sPreparedPayload);
		parent::LogPayload($sRawPayload, $sObfuscatedPayload, $oLog);
	}


}


class ActionSlackNotification extends ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_slack_notif',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-slack-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeHTML("message", array("allowed_values"=>null, "sql"=>'message', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_list_attributes", array("allowed_values"=>new ValueSetEnum("list,slack"), "display_style"=>'list', "sql"=>'include_list_attributes', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_user_info", array("allowed_values"=>new ValueSetEnum("yes,no"), "display_style"=>'radio_horizontal', "sql"=>'include_user_info', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_modify_button", array("allowed_values"=>new ValueSetEnum("yes,no"), "display_style"=>'radio_horizontal', "sql"=>'include_modify_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_delete_button", array("allowed_values"=>new ValueSetEnum("yes,no"), "display_style"=>'radio_horizontal', "sql"=>'include_delete_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_other_actions_button", array("allowed_values"=>new ValueSetEnum("yes,no,specify"), "display_style"=>'radio_horizontal', "sql"=>'include_other_actions_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("specified_other_actions", array("allowed_values"=>null, "sql"=>'specified_other_actions', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
    ),
    'fieldset:ActionSlackNotification:message' => 
    array (
      0 => 'message',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionSlackNotification:additionalelements' => 
    array (
      0 => 'include_list_attributes',
      1 => 'include_user_info',
      2 => 'include_modify_button',
      3 => 'include_delete_button',
      4 => 'include_other_actions_button',
      5 => 'specified_other_actions',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
;
	}


	/**
	 * @inheritDoc
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		$aSlackBlocks = array(
			'blocks' => array(),
		);

		// Prepare basis message
		$sMessage = static::TransformHTMLToSlackMarkup(MetaModel::ApplyParams($this->Get('message'), $aContextArgs));
		if(!empty($sMessage))
		{
			$aSlackBlocks['blocks'][] = array(
				'type' => 'section',
				'text' => array(
					'type' => 'mrkdwn',
					'text' => $sMessage,
				),
			);
		}

		// Prepare extra attributes
		$aBlock = $this->PrepareExtraAttributesForBlockKit($aContextArgs);
		if(!empty($aBlock))
		{
			$aSlackBlocks['blocks'][] = $aBlock;
		}

		// Prepare user information
		if($this->Get('include_user_info') === 'yes')
		{
			$aSlackBlocks['blocks'][] = $this->PrepareUserInfoForBlockKit($aContextArgs);
		}

		// Prepare action buttons
		$aBlock = $this->PrepareActionsForBlockKit($aContextArgs);
		if(!empty($aBlock))
		{
			$aSlackBlocks['blocks'][] = $aBlock;
		}

		return json_encode($aSlackBlocks);
	}


	/**
	 * Return a "block" array of attributes formatted for Slack "block kit" system, or null if the chosen list has no attributes
	 *
	 * @param array $aContextArgs
	 *
	 * @return null|array
	 */
	protected function PrepareExtraAttributesForBlockKit(array $aContextArgs)
	{
		/** @var \DBObject $oObject */
		$oObject = $aContextArgs['this->object()'];
		$sObjClass = get_class($oObject);

		// Retrieve attributes
		$aListItems = MetaModel::GetZListItems($sObjClass, $this->Get('include_list_attributes'));

		// No attributes in the list
		if(empty($aListItems))
		{
			return null;
		}

		// Prepare block structure
		$aBlock = array(
			'type' => 'section',
			'fields' => array(),
		);

		foreach($aListItems as $sAttCode)
		{
			$oAttDef = MetaModel::GetAttributeDef($sObjClass, $sAttCode);
			// We have to decode HTML entities as they are added on the value by \AttributeDefinition::GetAsHtml()
			$sValueAsHtml = html_entity_decode($oObject->GetAsHtml($sAttCode), ENT_QUOTES, 'UTF-8');
			$aBlock['fields'][] = array(
				'type' => 'mrkdwn',
				'text' => sprintf("*%s*\n%s", $oAttDef->GetLabel(), static::TransformHTMLToSlackMarkup($sValueAsHtml)),
			);
		}

		return $aBlock;
	}


	/**
	 * Return a "block" array for the current user information formatted for Slack "block kit" system
	 *
	 * @param array $aContextArgs
	 *
	 * @return array
	 */
	protected function PrepareUserInfoForBlockKit(array $aContextArgs)
	{
		// Get user info as accurate as possible
		$oUser = UserRights::GetUserObject();
		$oContact = $oUser->GetContactObject() ?: $oUser;

		$sContactClass = get_class($oContact);
		$sContactClassLabel = MetaModel::GetName($sContactClass);
		$sContactName = $oContact->GetName();
		$sContactUrl = ApplicationContext::MakeObjectUrl($sContactClass, $oContact->GetKey(), null, false);

		$aBlock = array(
			'type' => 'context',
			'elements' => array(
				array(
					'type' => 'mrkdwn',
					'text' => Dict::Format('ActionSlackNotification:Payload:BlockKit:UserInfo', $sContactName, $sContactUrl, $sContactClassLabel),
				),
			),
		);

		return $aBlock;
	}


	/**
	 * Return a "block" array of actions formatted for Slack "block kit" system, or null if no actions available
	 *
	 * @param array $aContextArgs
	 *
	 * @return null|array
	 */
	protected function PrepareActionsForBlockKit(array $aContextArgs)
	{
		$aActionElements = array();

		/** @var \DBObject $oObject */
		$oObject = $aContextArgs['this->object()'];
		$sObjClass = get_class($oObject);
		$iObjID = $oObject->GetKey();

		$sBaseURL = utils::GetAbsoluteUrlAppRoot();

		// Modify button
		if($this->Get('include_modify_button') === 'yes')
		{
			$aActionElements[] = array(
				'type' => 'button',
				'text' => array(
					'type' => 'plain_text',
					'text' => Dict::S('UI:Menu:Modify'),
				),
				'action_id' => 'modify',
				'url' => sprintf('%spages/UI.php?operation=modify&class=%s&id=%d', $sBaseURL, $sObjClass, $iObjID),
				'style' => 'primary',
			);
		}

		// Other actions buttons (transitions)
		$sIncludeOtherActionsButton = $this->Get('include_other_actions_button');
		if($sIncludeOtherActionsButton !== 'no')
		{
			$aTransitions = $oObject->EnumTransitions();
			$aStimuli = MetaModel::EnumStimuli($sObjClass);
			if ($sIncludeOtherActionsButton == 'yes')
			{
				$aAllowedStimuli = array_keys($aTransitions);
			}
			else
			{
				$aAllowedStimuli = preg_split('/\s*,\s*/', $this->Get('specified_other_actions'));
			}

			// Note: We don't filter stimuli on user rights, it's up to the notification creator
			// to tailored it regarding the recipients.
			foreach ($aAllowedStimuli as $sStimulusCode)
			{
				if (isset($aTransitions[$sStimulusCode]) && is_a($aStimuli[$sStimulusCode], StimulusUserAction::class))
				{
					$aActionElements[] = array(
						'type' => 'button',
						'text' => array(
							'type' => 'plain_text',
							'text' => $aStimuli[$sStimulusCode]->GetLabel(),
						),
						'action_id' => $sStimulusCode,
						'url' => sprintf('%spages/UI.php?operation=stimulus&stimulus=%s&class=%s&id=%d', $sBaseURL, $sStimulusCode, $sObjClass, $iObjID),
					);
				}
			}
		}

		// Delete button
		if($this->Get('include_delete_button') === 'yes')
		{
			$aActionElements[] = array(
				'type' => 'button',
				'text' => array(
					'type' => 'plain_text',
					'text' => Dict::S('UI:Menu:Delete'),
				),
				'action_id' => 'delete',
				'url' => sprintf('%spages/UI.php?operation=delete&class=%s&id=%d', $sBaseURL, $sObjClass, $iObjID),
				'style' => 'danger',
			);
		}

		// Prepare block
		$aBlock = (empty($aActionElements)) ? null : array(
			'type' => 'actions',
			'elements' => $aActionElements,
		);

		return $aBlock;
	}


	/**
	 * Return $sContent HTML transformed into Slack proper markup
	 *
	 * @param string $sContent
	 *
	 * @return string
	 */
	public static function TransformHTMLToSlackMarkup($sContent)
	{
		if(empty($sContent))
		{
			return $sContent;
		}

		$aReplacementsMatrix = array(
			array( array('<br />', '<br/>', '<br>'), "\n" ),
			array( array('<h1>', '</h1>'), array('*', '*') ),
			array( array('<h2>', '</h2>'), array('*', '*') ),
			array( array('<h3>', '</h3>'), array('*', '*') ),
			array( array('<strong>', '</strong>'), array('*', '*') ),
			array( array('<b>', '</b>'), array('*', '*') ),
			array( array('<em>', '</em>'), array('_', '_') ),
			array( array('<i>', '</i>'), array('_', '_') ),
			array( array('<del>', '</del>'), array('~', '~') ),
			array( array('<s>', '</s>'), array('~', '~') ),
			array( array('<li>', '</li>'), array('• ', '') ),
			array( array('<code>', '</code>'), array('`', '`') ),
			array( array('<pre>', '</pre>'), array('```', '```') ),
		);

		// Replace HTML tags (list must contain at least tags from the $aReplacementsMatrix)
		$sContent = strip_tags($sContent, '<h1><h2><h3><br><strong><b><em><i><del><s><li><code><pre><a>');
		foreach($aReplacementsMatrix as $aReplacements)
		{
			$sContent = str_replace($aReplacements[0], $aReplacements[1], $sContent);
		}

		// Replace hyperlinks
		preg_match_all('/<\s*a.*?href\s*=\s*(?:\"|\')(.*?)(?:\"|\')[^>]*>(.*?)<\s*?\/\s*?a\s*?>/i', $sContent, $aResult);
		for($iIdx = 0; $iIdx < count($aResult[0]); $iIdx++) {
			$sContent = str_replace($aResult[0][$iIdx], '<'.$aResult[1][$iIdx].'|'.$aResult[2][$iIdx].'>', $sContent);
		}

		return $sContent;
	}


}


class ActionRocketChatNotification extends ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_rocketchat_notif',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-rocketchat-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeHTML("message", array("allowed_values"=>null, "sql"=>'message', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("bot_alias", array("allowed_values"=>null, "sql"=>'bot_alias', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("bot_url_avatar", array("allowed_values"=>null, "sql"=>'bot_url_avatar', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("bot_emoji_avatar", array("allowed_values"=>null, "sql"=>'bot_emoji_avatar', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
    ),
    'fieldset:ActionRocketChatNotification:message' => 
    array (
      0 => 'message',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionRocketChatNotification:additionalelements' => 
    array (
      0 => 'bot_alias',
      1 => 'bot_url_avatar',
      2 => 'bot_emoji_avatar',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
;
	}


	/**
	 * @inheritDoc
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		$aData = array(
			'text' => static::TransformHTMLToRocketChatMarkup(MetaModel::ApplyParams($this->Get('message'), $aContextArgs)),
			'attachments' => array(),
		);

		// Bot information
		$aBotAttCodes = array('bot_alias' => 'alias', 'bot_url_avatar' => 'avatar', 'bot_emoji_avatar' => 'emoji');
		foreach($aBotAttCodes as $sBotAttCode => $sPropCode)
		{
			$sPropValue = MetaModel::ApplyParams($this->Get($sBotAttCode), $aContextArgs);
			if(empty($sPropValue) === false)
			{
				$aData[$sPropCode] = $sPropValue;
			}
		}

		return json_encode($aData);
	}


	/**
	 * Return $sContent HTML transformed into Rocket.Chat proper markup
	 *
	 * @param string $sContent
	 *
	 * @return string
	 */
	public static function TransformHTMLToRocketChatMarkup($sContent)
	{
		if(empty($sContent))
		{
			return $sContent;
		}

		$aReplacementsMatrix = array(
			array( array('<br />', '<br/>', '<br>'), "\n" ),
			array( array('<h1>', '</h1>'), array('*', '*') ),
			array( array('<h2>', '</h2>'), array('*', '*') ),
			array( array('<h3>', '</h3>'), array('*', '*') ),
			array( array('<strong>', '</strong>'), array('*', '*') ),
			array( array('<b>', '</b>'), array('*', '*') ),
			array( array('<em>', '</em>'), array('_', '_') ),
			array( array('<i>', '</i>'), array('_', '_') ),
			array( array('<del>', '</del>'), array('~', '~') ),
			array( array('<s>', '</s>'), array('~', '~') ),
			array( array('<li>', '</li>'), array('• ', '') ),
			array( array('<code>', '</code>'), array('`', '`') ),
			array( array('<pre>', '</pre>'), array('```', '```') ),
		);

		// Replace HTML tags
		$sContent = strip_tags($sContent, '<h1><h2><h3><br><strong><b><em><i><del><s><li><code><pre><a>');
		foreach($aReplacementsMatrix as $aReplacements)
		{
			$sContent = str_replace($aReplacements[0], $aReplacements[1], $sContent);
		}

		// Replace hyperlinks
		preg_match_all('/<\s*a.*?href\s*=\s*(?:\"|\')(.*?)(?:\"|\')[^>]*>(.*?)<\s*?\/\s*?a\s*?>/i', $sContent, $aResult);
		for($iIdx = 0; $iIdx < count($aResult[0]); $iIdx++) {
			$sContent = str_replace($aResult[0][$iIdx], '<'.$aResult[1][$iIdx].'|'.$aResult[2][$iIdx].'>', $sContent);
		}

		return $sContent;
	}


}


class ActionGoogleChatNotification extends ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_googlechat_notif',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-googlechat-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeText("message", array("allowed_values"=>null, "sql"=>'message', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionGoogleChatNotification:message' => 
    array (
      0 => 'message',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
;
	}


	/**
	 * @inheritDoc
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		$aData = array(
			'text' => MetaModel::ApplyParams($this->Get('message'), $aContextArgs),
		);

		return json_encode($aData);
	}


}


class ActionMicrosoftTeamsNotification extends ActionWebhook
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_microsoftteams_notif',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'combodo-webhook-integration/asset/img/icon-webhook-microsoftteams-48px.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("title", array("allowed_values"=>null, "sql"=>'title', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeHTML("message", array("allowed_values"=>null, "sql"=>'message', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("theme_color", array("allowed_values"=>null, "sql"=>'theme_color', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeURL("image_url", array("target"=>'', "allowed_values"=>null, "sql"=>'image_url', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_list_attributes", array("allowed_values"=>new ValueSetEnum("list,msteams"), "display_style"=>'list', "sql"=>'include_list_attributes', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_modify_button", array("allowed_values"=>new ValueSetEnum("yes,no"), "display_style"=>'radio_horizontal', "sql"=>'include_modify_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_delete_button", array("allowed_values"=>new ValueSetEnum("yes,no"), "display_style"=>'radio_horizontal', "sql"=>'include_delete_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("include_other_actions_button", array("allowed_values"=>new ValueSetEnum("yes,no,specify"), "display_style"=>'radio_horizontal', "sql"=>'include_other_actions_button', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("specified_other_actions", array("allowed_values"=>null, "sql"=>'specified_other_actions', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:ActionWebhook:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
    ),
    'fieldset:ActionWebhook:webhookconnection' => 
    array (
      0 => 'remoteapplicationconnection_id',
      1 => 'test_remoteapplicationconnection_id',
    ),
    'fieldset:ActionMicrosoftTeamsNotification:message' => 
    array (
      0 => 'title',
      1 => 'message',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:ActionMicrosoftTeamsNotification:additionalelements' => 
    array (
      0 => 'include_list_attributes',
      1 => 'include_modify_button',
      2 => 'include_delete_button',
      3 => 'include_other_actions_button',
      4 => 'specified_other_actions',
    ),
    'fieldset:ActionMicrosoftTeamsNotification:theme' => 
    array (
      0 => 'theme_color',
      1 => 'image_url',
    ),
    'fieldset:ActionWebhook:advancedparameters' => 
    array (
      0 => 'prepare_payload_callback',
      1 => 'process_response_callback',
    ),
  ),
  0 => 'trigger_list',
));
;
	}


	/**
	 * @inheritDoc
	 */
	protected function PreparePayload(array $aContextArgs, \EventNotification &$oLog)
	{
		$aData = array(
			'@type' => 'MessageCard',
			'@context' => 'http://schema.org/extensions',
		);
		$aSections = array(
			array(), // First section initialized for easier code below, but will be unset if empty at the end of the processing
		);
		$aPotentialActions = array();

		// Prepare theme
		// - Color
		$sThemeColor = MetaModel::ApplyParams($this->Get('theme_color'), $aContextArgs);
		if (strlen($sThemeColor) > 0) {
			$aData['themeColor'] = $sThemeColor;
		}
		// - Image
		$sImageUrl = MetaModel::ApplyParams($this->Get('image_url'), $aContextArgs);
		if (strlen($sImageUrl) > 0) {
			$aSections[0]['activityImage'] = $sImageUrl;
		}

		// Prepare title
		$sTitle = MetaModel::ApplyParams($this->Get('title'), $aContextArgs);
		if (strlen($sTitle) > 0) {
			// For summary
			$aData['summary'] = $sTitle;

			// For activity title
			$aSections[0]['activityTitle'] = $sTitle;
		}

		// Prepare message
		// Note: For now we don't convert HTML to Markdown as it is more limited on Teams end (and easier for us 😁)
		$sMessage = MetaModel::ApplyParams($this->Get('message'), $aContextArgs);
		if (strlen($sMessage) > 0) {
			$aSections[0]['activitySubtitle'] = $sMessage;
		}

		// Prepare extra attributes
		$aFacts = $this->PrepareExtraAttributesForMSTeamsAPI($aContextArgs);
		if(false === empty($aFacts))
		{
			$aSections[0]['facts'] = $aFacts;
		}

		// Add sections to data
		if (false === empty($aSections[0])) {
			$aData['sections'] = $aSections;
		}

		// Prepare action buttons
		$aActions = $this->PrepareActionsForMSTeamsAPI($aContextArgs);
		if(false == empty($aActions))
		{
			$aData['potentialAction'] = $aActions;
		}

		return json_encode($aData);
	}


	/**
	 * Return a "block" array of attributes formatted for Slack "block kit" system
	 *
	 * @param array $aContextArgs
	 *
	 * @return array
	 */
	protected function PrepareExtraAttributesForMSTeamsAPI(array $aContextArgs)
	{
		/** @var \DBObject $oObject */
		$oObject = $aContextArgs['this->object()'];
		$sObjClass = get_class($oObject);

		// Retrieve attributes
		$aListItems = MetaModel::GetZListItems($sObjClass, $this->Get('include_list_attributes'));

		// No attributes in the list
		if(empty($aListItems))
		{
			return array();
		}

		// Prepare facts structure
		$aFacts = array();

		foreach($aListItems as $sAttCode)
		{
			$oAttDef = MetaModel::GetAttributeDef($sObjClass, $sAttCode);
			// We have to decode HTML entities as they are added on the value by \AttributeDefinition::GetAsHtml()
			$sValueAsHtml = utils::HtmlEntityDecode($oObject->GetAsHtml($sAttCode));
			$aFacts[] = array(
				'name' => $oAttDef->GetLabel(),
				'value' => static::TransformHTMLToMSTeamsMarkup($sValueAsHtml),
			);
		}

		return $aFacts;
	}


	/**
	 * Return an array of actions formatted for Microsoft Teams "potential actions" system
	 *
	 * @param array $aContextArgs
	 *
	 * @return array
	 */
	protected function PrepareActionsForMSTeamsAPI(array $aContextArgs)
	{
		$aActionElements = array();

		/** @var \DBObject $oObject */
		$oObject = $aContextArgs['this->object()'];
		$sObjClass = get_class($oObject);
		$iObjID = $oObject->GetKey();

		$sBaseURL = utils::GetAbsoluteUrlAppRoot();

		// Modify button
		if($this->Get('include_modify_button') === 'yes')
		{
			$aActionElements[] = array(
				'@type' => 'OpenUri',
				'name' => Dict::S('UI:Menu:Modify'),
				'targets' => array(
					array(
						'os' => 'default',
						'uri' => sprintf('%spages/UI.php?operation=modify&class=%s&id=%d', $sBaseURL, $sObjClass, $iObjID),
					),
				),
			);
		}

		// Other actions buttons (transitions)
		$sIncludeOtherActionsButton = $this->Get('include_other_actions_button');
		if($sIncludeOtherActionsButton !== 'no')
		{
			$aTransitions = $oObject->EnumTransitions();
			$aStimuli = MetaModel::EnumStimuli($sObjClass);
			if ($sIncludeOtherActionsButton == 'yes')
			{
				$aAllowedStimuli = array_keys($aTransitions);
			}
			else
			{
				$aAllowedStimuli = preg_split('/\s*,\s*/', $this->Get('specified_other_actions'));
			}

			// Note: We don't filter stimuli on user rights, it's up to the notification creator
			// to tailored it regarding the recipients.
			foreach ($aAllowedStimuli as $sStimulusCode)
			{
				if (isset($aTransitions[$sStimulusCode]) && is_a($aStimuli[$sStimulusCode], StimulusUserAction::class))
				{
					$aActionElements[] = array(
						'@type' => 'OpenUri',
						'name' => $aStimuli[$sStimulusCode]->GetLabel(),
						'targets' => array(
							array(
								'os' => 'default',
								'uri' => sprintf('%spages/UI.php?operation=stimulus&stimulus=%s&class=%s&id=%d', $sBaseURL, $sStimulusCode, $sObjClass, $iObjID),
							),
						),
					);
				}
			}
		}

		// Delete button
		if($this->Get('include_delete_button') === 'yes')
		{
			$aActionElements[] = array(
				'@type' => 'OpenUri',
				'name' => Dict::S('UI:Menu:Delete'),
				'targets' => array(
					array(
						'os' => 'default',
						'uri' => sprintf('%spages/UI.php?operation=delete&class=%s&id=%d', $sBaseURL, $sObjClass, $iObjID),
					),
				),
			);
		}

		return $aActionElements;
	}


	/**
	 * Return $sContent HTML transformed into Microsoft Teams proper markup
	 *
	 * @param string $sContent
	 *
	 * @link https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#format-cards-with-markdown
	 * @return string
	 */
	public static function TransformHTMLToMSTeamsMarkup($sContent)
	{
		if(empty($sContent))
		{
			return $sContent;
		}

		$aReplacementsMatrix = array(
			array( array('<br />', '<br/>', '<br>'), "\n" ),
			array( array('<strong>', '</strong>'), array('**', '**') ),
			array( array('<b>', '</b>'), array('**', '**') ),
			array( array('<em>', '</em>'), array('_', '_') ),
			array( array('<i>', '</i>'), array('_', '_') ),
			array( array('<del>', '</del>'), array('~', '~') ),
			array( array('<s>', '</s>'), array('~', '~') ),
			array( array('<li>', '</li>'), array('-', '') ),
		);

		// Replace HTML tags (list must contain at least tags from the $aReplacementsMatrix)
		$sContent = strip_tags($sContent, '<h1><h2><h3><br><strong><b><em><i><del><s><li><code><pre><a>');
		foreach($aReplacementsMatrix as $aReplacements)
		{
			$sContent = str_replace($aReplacements[0], $aReplacements[1], $sContent);
		}

		// Replace hyperlinks
		preg_match_all('/<\s*a.*?href\s*=\s*(?:\"|\')(.*?)(?:\"|\')[^>]*>(.*?)<\s*?\/\s*?a\s*?>/i', $sContent, $aResult);
		for($iIdx = 0; $iIdx < count($aResult[0]); $iIdx++) {
			$sContent = str_replace($aResult[0][$iIdx], '['.$aResult[2][$iIdx].']('.$aResult[1][$iIdx].')', $sContent);
		}

		return $sContent;
	}


}
//
// Menus
//
class MenuCreation_combodo_webhook_integration extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['ConfigurationTools'] = new MenuGroup('ConfigurationTools', 90, 'fas fa-cog' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		if (UserRights::IsAdministrator())
		{
			$__comp_menus__['Integrations'] = new DashboardMenuNode('Integrations', dirname(__FILE__).'/integrations_dashboard.xml', $__comp_menus__['ConfigurationTools']->GetIndex(), 120 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		}
	}
} // class MenuCreation_combodo_webhook_integration
