<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'qv-plugin-itop-portals-ui/1.0.0',
	array(
		// Identification
		//
		'label' => 'Portals UI',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-structure/3.0.1',
			'itop-tickets/3.0.1',
			'itop-request-mgmt-itil/3.0.1',
			'itop-incident-mgmt-itil/3.0.1',
			'qv-plugin-itop-close-usr-rqst/1.0.0',
			'qv-plugin-itop-customer/1.0.0',
			'qv-plugin-itop-project-name/1.0.0',
			'qv-plugin-itop-request-customer-field/1.0.0'
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'vendor/autoload.php',
			'model.qv-plugin-itop-portals-ui.php', // Contains the PHP code generated by the "compilation" of datamodel.qv-plugin-itop-portals-ui.xml
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);


?>
