<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV3gzylm\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV3gzylm/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerV3gzylm.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerV3gzylm\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerV3gzylm\srcProdProjectContainer([
    'container.build_hash' => 'V3gzylm',
    'container.build_id' => 'c4837ac8',
    'container.build_time' => 1665500519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV3gzylm');
