<?php
//
// File generated by ... on the 2022-12-15T01:24:45+0100
// Please do not edit manually
//

/**
 * Classes and menus for qv-plugin-itop-customer (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class qv_customer extends Contact
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id'),
			'db_table' => 'qv_customer',
			'db_key_field' => 'client_nit',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'qv-plugin-itop-customer/../../images/users2-big.png'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("qv_customer_contact_name", array("allowed_values"=>null, "sql"=>'client_contact_name', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'name',
  1 => 'qv_customer_contact_name',
  2 => 'org_id',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'org_id',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'org_id',
));
;
	}


}