<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'browse_brick' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/BrowseBrickHelper.php';

return $this->services['browse_brick'] = new \Combodo\iTop\Portal\Helper\BrowseBrickHelper(${($_ = isset($this->services['security_helper']) ? $this->services['security_helper'] : $this->load('getSecurityHelperService.php')) && false ?: '_'}, ${($_ = isset($this->services['scope_validator']) ? $this->services['scope_validator'] : $this->load('getScopeValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['url_generator']) ? $this->services['url_generator'] : $this->getUrlGeneratorService()) && false ?: '_'});
