<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'brick_controller_helper' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/BrickControllerHelper.php';

return $this->services['brick_controller_helper'] = new \Combodo\iTop\Portal\Helper\BrickControllerHelper(${($_ = isset($this->services['request_manipulator']) ? $this->services['request_manipulator'] : $this->load('getRequestManipulatorService.php')) && false ?: '_'});
