<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache.app' shared service.

include_once $this->targetDirs[4].'/lib/psr/cache/src/CacheItemPoolInterface.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Adapter/AdapterInterface.php';
include_once $this->targetDirs[4].'/lib/psr/log/Psr/Log/LoggerAwareInterface.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/ResettableInterface.php';
include_once $this->targetDirs[4].'/lib/psr/log/Psr/Log/LoggerAwareTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Traits/AbstractTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Adapter/AbstractAdapter.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/PruneableInterface.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Traits/FilesystemCommonTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Traits/FilesystemTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/cache/Adapter/FilesystemAdapter.php';

$this->services['cache.app'] = $instance = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('FVXwuMcQx-', 0, ($this->targetDirs[0].'/pools'));

$instance->setLogger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : ($this->services['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())) && false ?: '_'});

return $instance;
