<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.stopwatch' shared service.

include_once $this->targetDirs[4].'/lib/symfony/stopwatch/Stopwatch.php';

return $this->services['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true);
