<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'object_form_handler' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/ObjectFormHandlerHelper.php';
include_once $this->targetDirs[4].'/lib/twig/twig/src/Extension/ExtensionInterface.php';
include_once $this->targetDirs[4].'/lib/twig/twig/src/Extension/AbstractExtension.php';
include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Twig/AppExtension.php';

return $this->services['object_form_handler'] = new \Combodo\iTop\Portal\Helper\ObjectFormHandlerHelper(${($_ = isset($this->services['request_manipulator']) ? $this->services['request_manipulator'] : $this->load('getRequestManipulatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['context_manipulator']) ? $this->services['context_manipulator'] : $this->load('getContextManipulatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['navigation_rule_helper']) ? $this->services['navigation_rule_helper'] : $this->load('getNavigationRuleHelperService.php')) && false ?: '_'}, ${($_ = isset($this->services['scope_validator']) ? $this->services['scope_validator'] : $this->load('getScopeValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['security_helper']) ? $this->services['security_helper'] : $this->load('getSecurityHelperService.php')) && false ?: '_'}, ${($_ = isset($this->services['url_generator']) ? $this->services['url_generator'] : $this->getUrlGeneratorService()) && false ?: '_'}, $this->parameters['combodo.portal.instance.conf'], $this->getEnv('string:PORTAL_ID'), ${($_ = isset($this->services['Combodo\\iTop\\Portal\\Twig\\AppExtension']) ? $this->services['Combodo\\iTop\\Portal\\Twig\\AppExtension'] : ($this->services['Combodo\\iTop\\Portal\\Twig\\AppExtension'] = new \Combodo\iTop\Portal\Twig\AppExtension())) && false ?: '_'}, $this);
