<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gjlkir6' shared service.

return $this->services['service_locator.gjlkir6'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['oBricksCollection' => function () {
    return ${($_ = isset($this->services['brick_collection']) ? $this->services['brick_collection'] : $this->load('getBrickCollectionService.php')) && false ?: '_'};
}]);
