<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'security_helper' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/SecurityHelper.php';

return $this->services['security_helper'] = new \Combodo\iTop\Portal\Helper\SecurityHelper(${($_ = isset($this->services['scope_validator']) ? $this->services['scope_validator'] : $this->load('getScopeValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['lifecycle_validator']) ? $this->services['lifecycle_validator'] : $this->load('getLifecycleValidatorService.php')) && false ?: '_'}, false);
