<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'session_message_helper' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/SessionMessageHelper.php';

return $this->services['session_message_helper'] = new \Combodo\iTop\Portal\Helper\SessionMessageHelper($this);
