<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.handler' shared service.

include_once $this->targetDirs[4].'/lib/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php';
include_once $this->targetDirs[4].'/lib/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php';
include_once $this->targetDirs[4].'/lib/symfony/http-foundation/Session/Storage/Handler/NativeSessionHandler.php';
include_once $this->targetDirs[4].'/lib/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php';

return $this->services['session.handler'] = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler(new \Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler(($this->targetDirs[0].'/sessions')));
