<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ui_extensions_helper' shared autowired service.

include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Helper/UIExtensionsHelper.php';

return $this->services['ui_extensions_helper'] = new \Combodo\iTop\Portal\Helper\UIExtensionsHelper($this);
