<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Combodo\iTop\Portal\Controller\UserProfileBrickController' shared autowired service.

include_once $this->targetDirs[4].'/lib/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[4].'/lib/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Controller/AbstractController.php';
include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Controller/BrickController.php';
include_once $this->targetDirs[4].'/env-production/itop-portal-base/portal/src/Controller/UserProfileBrickController.php';

return $this->services['Combodo\\iTop\\Portal\\Controller\\UserProfileBrickController'] = new \Combodo\iTop\Portal\Controller\UserProfileBrickController();
